### ISSUE TITLE
Getting Inspect Setup Locally

### ISSUE THREAD

**Issue by Keegnan** [bcgov/InspectInvasivesBC-Mussels-iOS#55]
**Describe the task**
Able to run the the app locally, run the app in an emulator.

**Acceptance Criteria**
- [x] App runs 
- [x] can be tested
- [x] emulator works

**Additional context**
- Should run the app in the emulator as an iPad mini (2019 - 2021 model)
-  some iPad min are different dimensions (7.9 inch & 8.3 inch)

**Comment by PaulGarewal** [comment]
# Progress Update

- Successfully built the inspect app in XCode with some minor tweaks to the code to account for some updated versions

![Image](https://github.com/user-attachments/assets/defd31ad-fcbd-4d7c-8ef0-dddb06144d83)

**Comment by PaulGarewal** [comment]
## Final Step 

- Final step in set up is to get Apple Developer Program access

![Image](https://github.com/user-attachments/assets/650ad5ef-3cb0-4099-aba5-232e3220b9d1)
